.TH "CHARISMA" "3" "Feb 2nd 2025" "Charisma 1.0.2"
.SH NAME
utf8_encode \- encode to UTF-8
.SH LIBRARY
Character decoder library (libcharisma, -lcharisma)
.SH SYNOPSIS
.nf
.B #include <charisma.h>
.PP
.BI "int32_t utf8_encode(uchar " c ", uint8_t *" buf ");"
.fi
.SH DESCRIPTION
Encodes the Unicode scalar value \f[I]c\f[R] as UTF-8 code unit(s) and writes them to \f[I]buf\f[R].
The length of \f[I]buf\f[R] must be at least four code units.
.PP
If \f[I]c\f[R] is not a valid Unicode scalar value, \f[I]buf\f[R] remains unchanged and a negative integer is returned.
.SH RETURN VALUE
Returns the number of code units written to \f[I]buf\f[R] on success.
Returns a negative integer if \f[I]c\f[R] is not a valid Unicode scalar value.
.SH SEE ALSO
.BR utf8_decode (3),
.BR utf16_encode (3),
.BR utf32_encode (3),
.BR uchar (3)
.SH AUTHOR
.UR https://railgunlabs.com
Railgun Labs
.UE .
.SH INTERNET RESOURCES
The online documentation is published on the
.UR https://railgunlabs.com/charisma
Railgun Labs website
.UE .
.SH LICENSING
Charisma is distributed with its end-user license agreement (EULA).
Please review the agreement for information on terms & conditions for accessing or otherwise using Charisma and for a DISCLAIMER OF ALL WARRANTIES.